services:
  redis:
    image: redis:alpine
    container_name: redis_broker

  miner:
    build: ./miner
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    env_file: .env

  visualizer:
    build: ./visualizer
    depends_on:
      - redis
    volumes:
      - ./charts:/app/charts # Comparte carpeta local con la del contenedor
    environment:
      - REDIS_HOST=redis
